### ISSUE TITLE
Volume subfolders not reflected in URL

### ISSUE THREAD

**Issue by jawngee** [sjelfull/craft3-imgix#10]
If I've defined a subfolder for the asset volume, the generated imgix URLs don't include the subpath which leads to broken 404 error'd images.

Am I doing something wrong?

(Sorry, initially commented on the wrong repo).

**Comment by skramstad** [comment]
Did you solve it?

If you have a subfolder, just add it in your imgix path.
` 
   'imgixDomains'   => [
    	'images' => 'somename.imgix.net/subfoldername',
    ], 
`

**Comment by sjelfull** [comment]
@jawngee does ☝️ fix it?

**Comment by leevigraham** [comment]
FYI @skramstad fix breaks purging.

**Comment by leevigraham** [comment]
Rather than change the way the ImgixModel works to fix the purging issue I've changed the way the purging url generation logic works to use the same logic as the ImgixModel

https://github.com/sjelfull/craft3-imgix/pull/28

**Comment by sjelfull** [comment]
The fix from #28 is out now in 3.0.0
