### ISSUE TITLE
imgixDomains domain is not being pulled through

### ISSUE THREAD

**Issue by Factored-Dan** [sjelfull/craft3-imgix#13]
I have set this within imgix.php:

`'imgixDomains'   => ['somesite.imgix.net'],`

and in the twig file i have set a basic image call:

```
{% set firstImage = craft.imgix.transformImage( image, { width: 400, height: 350 }) %}
<img src="{{ firstImage.getUrl() }}" alt="test image">
```
And the output in the src attribute is:

`https:///cta-img-4.jpg?fp-x=0.5&fp-y=0.5&h=350&ixlib=php-2.1.1&w=400`

As you can see, the domain (somesite.imgix.net) is missing. Is this a bug, or am I missing something?

NOTE: I have not set an apiKey as I have not enabled Secure URLs for this source on imgix.com. If that is a factor, let me know.

**Comment by sjelfull** [comment]
Hey, so the problem here is that you haven't mapped the volume handle to the domain.

Your example should look more like this:
```php
'imgixDomains' => ['volumeHandle' => 'somesite.imgix.net'],
```

The apiKey is only needed if you need to purge urls.
