### ISSUE TITLE
html validation error missing `sizes` attribute on <img> element with `srcset`

### ISSUE THREAD

**Issue by boldenamsterdam** [sjelfull/craft3-imgix#15]
Hi @sjelfull 

When we run w3c HTML validation over our HTML, that makes use of the img.srcset({}) function, we get a validation error.

I was also not aware we had to look it up but according the what-wg when you use a <img> element with a srcset attribute it should also contain the attribute sizes

> If the srcset attribute is present and has any image candidate strings using a width descriptor, the sizes attribute must also be present, and is a sizes attribute. The sizes attribute contributes the source size to the source set (if no source element was selected).

[https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-sizes](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-sizes)

Not really sure what a nice way would be to fix. Cause when you make use of lazyload some lazyload scripts need to have the data- attribute in-front of it and at the same time you should also be able to specify the sizes in the sizes attribute.

**Comment by sjelfull** [comment]
Could you set `sizes` with `image.srcset({ sizes: '...' })`?

**Comment by boldenamsterdam** [comment]
Hi @sjelfull ,

JUP that works, awesome ✌🏼

And when someone tries to let it work with the JS library 'lazysizes' (or any another lazyloading library) that makes use of a custom sizes attribute you can achieve this by making a string of the attribute.

So without custom attributes:
```image.srcset({ sizes: '...' })```

With custom attributes:
```image.srcset({ 'data-sizes': '...' })```

**Comment by sjelfull** [comment]
Excellent. Feel free to submit a PR with any improvements to the docs you see fit.
