### ISSUE TITLE
Better passthrough support when imgixDomain is null

### ISSUE THREAD

**Issue by davist11** [sjelfull/craft3-imgix#20]
I'm wondering if there is the possibility of adding better support when a volume _isn't_ found in the `imgixDomains`. For example if my template code looks like

```twig
{% set imgixImage = craft.imgix.transformImage(asset, transform, {
    auto: 'format, compress',
}) %}

<img src="{{ imgixImage.url }}">
```

If my asset can pull from either an s3 volume (that's using imgix) or a local volume (that isn't using imgix and isn't in the `imgixDomains` array), it would be really cool to better support this use case. I _think_ it would be a matter of setting the `$domain` to be the asset volumes URL (and maybe some other values).

https://github.com/sjelfull/craft3-imgix/blob/2b18f4d3d902cc9a315f465941919bf0d8bf1e3c/src/models/ImgixModel.php#L186-L191

Currently it returns a URL like:
`https:///Work-Hero.jpg?auto=format%2C%20compress&fp-x=0.5&fp-y=0.5&h=396&ixlib=php-2.1.1&mode=crop&w=660&s=fc598c566c821d1251e28f762347b597`

Does that make sense? Is that something you would be willing to add support for (or merge a PR if I were to dive into it)?

**Comment by sjelfull** [comment]
Thanks, I think this makes sense, so would be great if you could submit a PR!

**Comment by davist11** [comment]
Sweet, created that PR, was simpler than I thought!

https://github.com/sjelfull/craft3-imgix/pull/26
