### ISSUE TITLE
Deprecated getUri() error

### ISSUE THREAD

**Issue by skramstad** [sjelfull/craft3-imgix#5]
`craft\elements\Asset::getUri() has been deprecated. Use getPath() instead.`

Running Craft 3 RC13.

**Comment by romainpoirier** [comment]
Still running in the last version of this plugin, using last Craft CMS version (3.0.13.2).

@skramstad, you can change `$this->imagePath  = $image->getUri();` to `$this->imagePath  = $image->getPath();` in `src/models/ImgixModel.php` line 193 to avoid this error.

Please @sjelfull, can you correct this in the next release?

**Comment by sjelfull** [comment]
Sorry, been way to busy to follow up on anything. I'm always open to pull requests.

That being said, I will try to take a look at it asap.

**Comment by sjelfull** [comment]
Version 2.0.4, out soon, should fix this.
