### ISSUE TITLE
Strangely formatted URLs

### ISSUE THREAD

**Issue by j-greig** [sjelfull/craft3-imgix#6]
Something weird is happening with the imgix urls (running locally with Valet on a multi-locale setup)

The URL is coming out as :
`https://team/Gabriele-Bernatzky.jpg?fp-x=0.5&fp-y=0.5&h=350&ixlib=php-1.1.0&w=400`

when it should be more like
`http://gh-hoskins.imgix.net/Team/Gabriele-Bernatzky.jpg`

I’ve set `'imgixDomains'   => ['http://gh-hoskins.imgix.net/']` in `config/imgix.php` (edited)

**Comment by sjelfull** [comment]
This was because the domains wasn't mapped correctly with their belonging Volume handles.

The right syntax is:

```php
...
'imgixDomains' => ['volumeHandle' => 'http://gh-hoskins.imgix.net/']
...
```
