### ISSUE TITLE
Focal points and crop configuration is overridden 

### ISSUE THREAD

**Issue by dictions** [sjelfull/craft3-imgix#8]
This logic is making it impossible to manually set the focal points via a transform, and is also overriding the `crop` query param provided by imgix:

```php
if ( !empty($focalPoint) ) {
    $defaultOptions['fp-x'] = $focalPoint['x'];
    $defaultOptions['fp-y'] = $focalPoint['y'];
}
```

[Found here.](https://github.com/sjelfull/craft3-imgix/blob/master/src/models/ImgixModel.php#L196)

**Comment by wfendler** [comment]
Looks like you can override this by adding it to the URL yourself. It would be great to have crop and focal point support built in! I moved from Imager to Imgix to get the improvements on these features. Looks like it'll just need to be manually added for now.

```
{% set imgixUrl = craft.imgix.transformImage(image, {
	width: 900
}).getUrl() %}

<img src="{{ imgixUrl }}&fp-x={{ image.focalPoint.x }}&fp-y={{ image.focalPoint.y }}" alt="">
```

**Comment by sjelfull** [comment]
There was a bug where the default options (which the focal point was a part of) was overriding whatever you passed.

Version 2.0.4, out soon, makes it possible to override the focal point.

```{% set firstImage = craft.imgix.transformImage( asset, { width: 400, height: 350, x: 0.25, y: 0.70 }) %}```
